In [33]:
import matplotlib.pyplot as plt
import numpy as np
from math import pi

In [34]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, transpile
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

In [35]:
backend = BasicAer.get_backend('unitary_simulator')

In [36]:
q = QuantumRegister(1)

In [37]:
qc = QuantumCircuit(q)
qc.u(pi/2, pi/4,pi/8,q)
qc.draw()

┌────────────────┐
q6: ┤ U(π/2,π/4,π/8) ├
    └────────────────┘

In [38]:
job =backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   , -0.653-0.271j],
       [ 0.5  +0.5j  ,  0.271+0.653j]])

In [39]:
#Pゲート
qc =QuantumCircuit(q)
qc.p(pi/2, q)
qc.draw()

┌────────┐
q6: ┤ P(π/2) ├
    └────────┘

In [40]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [41]:
#恒等ゲートId = p(0)
qc = QuantumCircuit(q)
qc.id(q)
qc.draw()

┌───┐
q6: ┤ I ├
    └───┘

In [42]:
job =backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [43]:
#パウリゲート
qc = QuantumCircuit(q)
qc.x(q)
qc.draw()

┌───┐
q6: ┤ X ├
    └───┘

In [44]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [45]:
#ビットアンドフェーズフリップゲート
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

┌───┐
q6: ┤ Y ├
    └───┘

In [46]:
job =backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])

In [48]:
#S=√Zフェーズ
qc = QuantumCircuit(q)
qc.s(q)
qc.draw()

┌───┐
q6: ┤ S ├
    └───┘

In [49]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

In [50]:
#H アダマールゲート
qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

┌───┐
q6: ┤ H ├
    └───┘

In [51]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j,  0.707-0.j],
       [ 0.707+0.j, -0.707+0.j]])

In [52]:
#S転置共役
qc = QuantumCircuit(q)
qc.sdg(q)
qc.draw()

┌─────┐
q6: ┤ Sdg ├
    └─────┘

In [53]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j]])

In [55]:
qc = QuantumCircuit(q)
qc.t(q)
qc.draw()

┌───┐
q6: ┤ T ├
    └───┘

In [56]:
job =backend.run(transpile(qc,backend))
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [58]:
#標準回転
qc = QuantumCircuit(q)
qc.rx(pi/2, q)
qc.draw()

┌─────────┐
q6: ┤ Rx(π/2) ├
    └─────────┘

In [59]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   , -0.   -0.707j],
       [ 0.   -0.707j,  0.707+0.j   ]])

In [61]:
#Y軸まわりの回転
qc = QuantumCircuit(q)
qc.ry(pi/2, q)
qc.draw()

┌─────────┐
q6: ┤ Ry(π/2) ├
    └─────────┘

In [62]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j, -0.707+0.j],
       [ 0.707+0.j,  0.707+0.j]])

In [64]:
#Zまわりの回転
qc= QuantumCircuit(q)
qc.rz(pi/2,q)
qc.draw()

┌─────────┐
q6: ┤ Rz(π/2) ├
    └─────────┘

In [65]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[0.707-0.707j, 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

In [67]:
#2量子ビット場合
q= QuantumRegister(2)

In [68]:
#制御パウリゲート
qc = QuantumCircuit(q)
qc.cx(q[0],q[1])
qc.draw()

q19_0: ──■──
       ┌─┴─┐
q19_1: ┤ X ├
       └───┘

In [69]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j]])

In [70]:
#制御Ｙゲート
qc = QuantumCircuit(q)
qc.cy(q[0],q[1])
qc.draw()

q19_0: ──■──
       ┌─┴─┐
q19_1: ┤ Y ├
       └───┘

In [71]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.-1.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j]])

In [72]:
#制御Ｚゲート
qc = QuantumCircuit(q)
qc.cz(q[0],q[1])
qc.draw()

q19_0: ─■─
        │ 
q19_1: ─■─

In [73]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.-0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.-0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [75]:
#制御回転ゲート
qc = QuantumCircuit(q)
qc.crz(pi/2,q[0],q[1])
qc.draw()

q19_0: ─────■─────
       ┌────┴────┐
q19_1: ┤ Rz(π/2) ├
       └─────────┘

In [76]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707-0.707j, 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.707+0.707j]])

In [77]:
#制御位相回転
qc = QuantumCircuit(q)
qc.cp(pi/2,q[0],q[1])
qc.draw()

q19_0: ─■───────
        │P(π/2) 
q19_1: ─■───────

In [78]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j]])

In [80]:
#制御u回転
qc = QuantumCircuit(q)
qc.cu(pi/2,pi/2,pi/2,0,q[0],q[1])
qc.draw()

q19_0: ─────────■──────────
       ┌────────┴─────────┐
q19_1: ┤ U(π/2,π/2,π/2,0) ├
       └──────────────────┘

In [81]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[ 1.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.j   ,  0.707+0.j   ,  0.   +0.j   , -0.   -0.707j],
       [ 0.   +0.j   ,  0.   +0.j   ,  1.   +0.j   ,  0.   +0.j   ],
       [ 0.   +0.j   ,  0.   +0.707j,  0.   +0.j   , -0.707+0.j   ]])

In [82]:
#SWAPGETA
qc = QuantumCircuit(q)
qc.swap(q[0],[1])
qc.draw()

q19_0: ─X─
        │ 
q19_1: ─X─

In [83]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [88]:
q = QuantumRegister(3)

In [91]:
#ToffoliゲートCXXゲート
qc = QuantumCircuit(q)
qc.ccx(q[0],q[1],q[2])
qc.draw()

q27_0: ──■──
         │  
q27_1: ──■──
       ┌─┴─┐
q27_2: ┤ X ├
       └───┘

In [92]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [93]:
#CSWAPゲート
qc = QuantumCircuit(q)
qc.cswap(q[0],q[1],q[2])
qc.draw()

q27_0: ─■─
        │ 
q27_1: ─X─
        │ 
q27_2: ─X─

In [94]:
job = backend.run(transpile(qc, backend))
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.-0.j]])

In [95]:
#非ユニタリ操作
q = QuantumRegister(1)
c = ClassicalRegister(1)

In [96]:
qc = QuantumCircuit(q, c)
qc.measure(q,c)
qc.draw()

┌─┐
 q31: ┤M├
      └╥┘
c0: 1/═╩═
       0

In [97]:
backend =BasicAer.get_backend('qasm_simulator')
job = backend.run(transpile(qc,backend))
job.result().get_counts(qc)

{'0': 1024}

In [99]:
qc = QuantumCircuit(q,c)
qc.h(q)
qc.measure(q,c)
qc.draw()

┌───┐┌─┐
 q31: ┤ H ├┤M├
      └───┘└╥┘
c0: 1/══════╩═
            0

In [102]:
job = backend.run(transpile(qc,backend))
job.result().get_counts(qc)

{'0': 498, '1': 526}

In [105]:
#reset
qc = QuantumCircuit(q,c)
qc.h(q)
qc.reset(q[0])
qc.measure(q,c)
qc.draw()

┌───┐     ┌─┐
 q31: ┤ H ├─|0>─┤M├
      └───┘     └╥┘
c0: 1/═══════════╩═
                 0

In [107]:
job = backend.run(transpile(qc, backend))
job.result().get_counts(qc)

{'0': 1024}

In [111]:
qc = QuantumCircuit(q,c)
qc.h(q)
qc.measure(q,c)
qc.x(q[0]).c_if(c,0)
qc.measure(q, c)
qc.draw()

┌───┐┌─┐ ┌───┐ ┌─┐
 q31: ┤ H ├┤M├─┤ X ├─┤M├
      └───┘└╥┘ └─╥─┘ └╥┘
            ║ ┌──╨──┐ ║ 
c0: 1/══════╩═╡ 0x0 ╞═╩═
            0 └─────┘ 0

In [127]:
import math
desired_vector = [
    1 / math.sqrt(16) * complex(0, 1),
    1 / math.sqrt(8) * complex(1, 0),
    1 / math.sqrt(16) * complex(1, 1),
    0,
    0,
    1 / math.sqrt(8) * complex(1, 2),
    1 / math.sqrt(16) * complex(1, 0),
    0]


q = QuantumRegister(3)

qc = QuantumCircuit(q)

qc.initialize(desired_vector, [q[0],q[1],q[2]])
qc.draw()

┌───────────────────────────────────────────────────────────────────┐
q58_0: ┤0                                                                  ├
       │                                                                   │
q58_1: ┤1 Initialize(0.25j,0.35355,0.25+0.25j,0,0,0.35355+0.70711j,0.25,0) ├
       │                                                                   │
q58_2: ┤2                                                                  ├
       └───────────────────────────────────────────────────────────────────┘

In [128]:
backend = BasicAer.get_backend('statevector_simulator')
job =backend.run(transpile(qc, backend))
qc_state = job.result().get_statevector(qc)
qc_state

array([1.66533454e-16+2.50000000e-01j, 3.53553391e-01-5.55111512e-17j,
       2.50000000e-01+2.50000000e-01j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 3.53553391e-01+7.07106781e-01j,
       2.50000000e-01-9.02056208e-17j, 0.00000000e+00+0.00000000e+00j])

In [129]:
state_fidelity(desired_vector, qc_state)

1.0000000000000004

In [130]:
import qiskit.tools.jupyter
%qiskit_version_table
%qiskit_copyright